#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
filename='/home/chrisd/playlists.txt'
cmd='mplayer'
cmdargs='-really-quiet -msgcolor'
if [[ -f $filename ]]
then
	echo "* Using $filename"
else
	echo "* Could not find $filename, please make sure it exists"
	exit 1
fi
cmdfile=`which $cmd 2>/dev/null`
if [[ -x $cmdfile ]]
then
	echo "* Using $cmd to play the media"
else
	echo "* Could not execute $cmd"
	echo "  - You may not have $cmd installed"
	echo "  - You may not have permission to execute $cmd"
	exit 1
fi
if [[ -n $1 ]]
then
	if [[ "$1" == "rand" ]]
	then
		lines=`grep -c --regexp=.* $filename`
		num=`expr $RANDOM % $lines + 1`
		line=`sed -n ${num}p $filename`
		echo "* Randomly picked $line"
		$cmd $cmdargs "$line"
	else
		echo "* Searching for $1"
		$cmd $cmdargs `grep $1 $filename`
	fi
else
	echo "* Displaying all streams"
	cat $filename
fi
